export enum SettingKeys {
  PreviousFeaturedComp = "previous-featured-comp",
  JoinLimit = "join-limit",
  Stake = "stake",
  MinAmountWithdrawalVoucher = "min-amount-voucher",
  MaxAmountWithdrawalVoucher = "max-amount-voucher",
  MinAmountWithdrawal = "min-amount",
  MaxAmountWithdrawal = "max-amount",
  DisableVoucher = "disable-voucher",
  RebuyTokenPoint = "rebuy-token-point",
  ReverseStake = "reverse-stake",
  DisableNotification = "disable-notification",
  ReportEmail = "report-email",
  VoucherJoinThreshold = "voucher-join-threshold",
  VoucherJoinReceive = "voucher-join-receive",
  RebuyTokenJoinThreshold = "rebuy-token-join-threshold",
  RebuyTokenJoinReceive = "rebuy-token-join-receive",
  RebuyTokenExpiredDays = "rebuy-token-expired-days",
  DisableMaxPP = "disable-maxpp",
  MaxJoinGroupTimes = "max-join-group-times",
  MaxJoinPunterGroupTimes = "max-join-punter-group-times",
  FlashBannerForFreeQuickPick = "flash-banner-for-free-quick-pick",
  FormatNotifEventUpcoming = "format-notif-event-upcoming",
  EventUpcomingSendNotifThreshold = "event-upcoming-send-notif-threshold",
  MaxNudgedPunterGroupTimes = "max-nudged-punter-group-times",
  FormatNotifInviteJoinGroup = "format-notif-invite-join-group",
  PercentOfBetSlipToJackpot = "percent-of-bet-slip-to-jackpot",
  FormatNotifGroupWinJackpot = "format-notif-group-win-jackpot",
  FormatNotifUserWinJackpot = "format-notif-user-win-jackpot",
  MinimumJackpotPool = "minimum-jackpot-pool",
  ConfigBetYourselfBetslip = "config-bet-yourself-betslip",
  MaximumBetYourselfOdds = "maximum-bet-yourself-odds",
  MinimumBetYourselfOdds = "minimum-bet-yourself-odds",
  FormatNotifEventUpcomingTipping = "format-notif-event-upcoming-tipping",
  TippingKeepingPercent = "tipping-keeping-percent",
  ConfigCompUpcomingSendNoti = "config-comp-upcoming-send-noti",
  AlertNotResultedEvent = "alert-not-resulted-event",
  SendCompetitionReport = "send-competition-report",
}

export enum SettingSections {
  Competition = "competition",
  Voucher = "voucher",
  Withdrawal = "withdrawal",
  RebuyToken = "rebuy-token",
}
